spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gymdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gymuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:gympass}
